name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t react-multi-img -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true react-multi-img npm test
      - run: docker build -t multi-client  ./client
      - run: docker build -t multi-nginx  ./nginx
      - run: docker build -t multi-server  ./server
      - run: docker build -t multi-worker  ./worker

      
    